-- Pohled je aktualizovatelny
CREATE VIEW Napoje AS
SELECT ZBOZ.NAZ, ZBOZ.KAT, ZBOZ.JCEN, ZBOZ.JEDN, ZBOZ.SKLAD
FROM dbo.ZBOZ 
JOIN KAT ON(ZBOZ.KAT = KAT.KAT) 
WHERE ZBOZ.KAT IN
(
    SELECT KAT.KAT 
    FROM KAT 
    WHERE KAT.NADR LIKE 'nap%'
);